frontend/src/pages/RecipeDetailPage.jsx
- Voice controls (Play, Pause, Resume, Cancel, Speed) via SpeechSynthesis.
- Slider to seek through spoken content with proper sync.
- Skip forward/back now moves to the correct sentence without repeating.
- Voice resets to start after speech ends.
- Unified voice control UI across all recipe pages.
- Comment input now uses double quotes for state initialization.
=> Integrate Voice Playback on Recipe Pages

frontend/src/App.css, frontend/src/components/Header.jsx, frontend/src/pages/About.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/RecipeDetailPage.jsx, frontend/src/pages/Register.jsx, frontend/src/pages/beverages.jsx, frontend/src/pages/dessert.jsx, frontend/src/pages/nonveg.jsx, frontend/src/pages/veg.jsx, frontend/src/styles/About.css, frontend/src/styles/RecipeDetail.css, frontend/src/styles/UserProfile.css
**UI Enhancements & Dark Mode Improvements**
- Improved UserProfile page: better layout, tags, and card styling
- Updated Veg, Nonveg, Desserts & Beverages listing pages for consistent card grids, search bar styling, and dark mode compatibility
- Enhanced RecipeDetailPage with cleaner like & comment sections, fallback images, and improved typography
- Refactored and unified CSS for consistent theme, better responsiveness, and smoother user experience
=> Enhance Mobile Responsiveness (Issue #2)

backend/package-lock.json, backend/package.json, frontend/src/pages/Register.jsx, frontend/src/styles/Register.css
✅ Changes Made
- Redesigned the registration form to a centered card layout with better spacing and alignment.
- Updated input fields with rounded borders and modern styling for a cleaner look.
- Added side-by-side alignment for Username & Email, and Age & Gender fields.
- Changed the Register button styling to a modern gradient with shadow effects.
- Improved checkbox and Terms & Privacy Policy section styling for better visibility.
- Enhanced overall responsiveness for different screen sizes.
🎯 Before vs After
Before: The form was stretched across the entire page with minimal styling and poor hierarchy.
After: The form is now compact, centered, and visually appealing, with improved readability and alignment.
BEFORE:
AFTER:
closes #79
=> Improved UI of Join Now

frontend/src/components/CTASection.jsx, frontend/src/components/CategoriesSection.jsx, frontend/src/components/FeaturesSection.jsx, frontend/src/components/HowItWorksSection.jsx, frontend/src/pages/RecipeHome.jsx
This PR introduces visually engaging and responsive UI enhancements to the home page of Recipedia. The updates focus on improving user experience through dynamic rendering, hover effects, and animated transitions across key sections.
- **Categories Section** (`CategoriesSection.jsx`)
- Added animated category cards with hover overlays, gradient borders, and interactive badges.
- Included trending indicators and recipe counts for each category.
- Integrated Lucide icons for visual appeal.
- **Features Section** (`FeaturesSection.jsx`)
- Introduced animated feature items with hover effects, progress bars, and floating UI elements.
- Used IntersectionObserver for smooth reveal animations on scroll.
- Enhanced visual hierarchy with gradients and iconography.
- **CTA Section** …
=> Enhanced Home Page Sections with Interactive Animations

frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/components/AboutCTASection.jsx, frontend/src/components/AboutFeaturesSection.jsx, frontend/src/components/AboutHeroSection.jsx, frontend/src/components/AboutMissionSection.jsx, frontend/src/components/AboutValuesSection.jsx, frontend/src/pages/About.jsx, frontend/src/pages/RecipeHome.jsx
This PR introduces a modular and visually engaging redesign of the About Us page. It improves user experience through animation, responsive design, and clearer messaging about Recipedia’s mission and features.
---
- **Modular Components Added:**
- `AboutHeroSection.jsx`: Hero banner with animated background and intro text.
- `AboutMissionSection.jsx`: Mission highlights with scroll-triggered animations.
- `AboutFeaturesSection.jsx`: Key features grid with icons and transitions.
- `AboutCTASection.jsx`: Call-to-action section encouraging user registration.
- **Styling Enhancements:**
- Scoped CSS classes for better maintainability.
- Unified color variables (`--auth-primary-color`, etc.) for consistent theming.
- Responsive layout improvements for mobile and tablet views.
--- …
=> Enhance About Us Page with Modular Components

frontend/src/pages/RecipeDetailPage.jsx
This PR addresses Issue #139 by enhancing the UI of the Audio Overview section and Adding Subtitles on the Recipe Detail Page
- Redesigned layout for audio controls
- Implemented simple subtitles synced with audio
- Applied modern UI/UX improvements: hover, focus, and responsive styling
- Matched visual theme to overall site design
**RecipeDetailPage.jsx**
https://github.com/user-attachments/assets/1007fcbd-1e52-40d3-9d6a-5481e72f5485
=> Enhanced UI of Audio Overview section and Added Subtitles

frontend/src/components/CategoriesSection.jsx, frontend/src/pages/RecipeListPage.jsx, frontend/src/pages/veg.jsx
- updated dark-them-styles
- 
@MeghanaDG04
=> Updated dark-styles

frontend/src/components/CategoriesSection.jsx, frontend/src/components/HowItWorksSection.jsx
Fix #145 
Fixed the hidden title text that was not visible on the cards in the dark mode. The UI has been improved and the changed was tested perfectly. No other breakdowns were caused while these changes were made.
**Earler:-**  
**After my fix:-**
@MeghanaDG04  Please merge this PR if everything is fine from your end too.
Thanks
=> fixed the hidden title text on cards in dark mode

frontend/src/components/Footer.jsx
=> fix issue 73

backend/package-lock.json, backend/package.json, frontend/src/components/HowItWorksSection.jsx, frontend/src/components/StepCard.jsx, frontend/src/components/stepsData.jsx
Create Your Account card → Navigates to the account creation page.
Add Your Recipe card → Navigates to the recipe submission page.
Linked frontend card buttons to the respective backend routes.
Ensured smooth navigation between frontend UI and backend endpoints.
Verified that clicking on Create Your Account opens the signup flow.
Verified that clicking on Add Your Recipe navigates to the recipe form.
https://github.com/user-attachments/assets/c487dd2c-868c-4d34-8796-0e203b7b7529
Fixes #133
=> Added backend routes 

frontend/src/components/HeroSection.jsx
=> arrows disappear after passing from herosection

frontend/src/components/Header.jsx, frontend/src/components/HeroSection.jsx
Reverts MeghanaDG04/RECIPEDIA#176
=> Revert "fixs : update HeroSection component and HeadeSection toggle button"

frontend/src/components/AudioOverview.jsx, frontend/src/pages/RecipeDetailPage.jsx
- **Modular Component**: Extracted audio logic into `AudioOverview.jsx` for better separation of concerns and reusability.
- **Auto-Chaining Speech**: Fixed speech synthesis to automatically play the next section, improving flow and UX.
- **Speed Control & Seek Bar**: Added interactive controls for playback speed and progress seeking.
- **Responsive UI**: Designed with Tailwind CSS and Framer Motion for smooth animations and mobile-first responsiveness.
- **Android Compatibility**: Added fallback logic for speech synthesis on Android devices.
- **Improved Subtitle Rendering**: Displays real-time spoken content with dynamic preview.
- Removed redundant inline speech logic from `RecipeDetailPage.jsx`.
- Cleaned up state management and ensured proper lifecycle handling with `useEffect`.
- …
=> Enhanced Audio Overview for Recipe Detail Page

frontend/src/App.jsx, frontend/src/components/ScrollReset.jsx
- now whenever user will mount on other route page it will come from starting position.
Issue: #167
=> Scroll reset added

frontend/src/components/HeroSection.jsx
I have change position of hero section now it is visible and also looking good.
=> Updated Hero Section which is hidden under the navbar

frontend/src/components/Footer.jsx
Fixes #179
Added a responsive footer component styled with Tailwind CSS.  
- Includes navigation links, recipe categories, contact info, and social media icons.  
- Added hover and accessibility features for better UX.  
- Footer adapts across screen sizes using a responsive grid layout.
=> Added responsive footer component using Tailwind CSS

frontend/src/components/CategoriesSection.jsx
https://github.com/user-attachments/assets/85c0a19c-41e0-43d2-9cb6-fbf9a0c1ff40
Improved hover effect for category label in recipe done.
issue no #184 
@MeghanaDG04
=> Improve hover effect for category label in recipe

frontend/src/components/Footer.jsx, frontend/src/styles/Footer.css
this pr solves the alignment of  footer .
Fixes #179 
before---
after---
=> [ENHANCE]: footer alignment

frontend/package-lock.json, frontend/src/pages/Explore.jsx
This PR refactors the `Explore.jsx` page by removing hardcoded recipe arrays and replacing them with dynamic imports from a centralized `recipes.json` file. It improves maintainability, reduces redundancy, and aligns with scalable data management practices.
- 🔥 Removed hardcoded `vegetarianRecipes`, `nonVegRecipes`, `dessertRecipes`, and `beverageRecipes` arrays.
- 📦 Integrated `recipes.json` and filtered/mapped data dynamically by category.
- 🧹 Cleaned up unused JSON references.
- 🔧 Updated `package-lock.json` due to dependency resolution during build.
- `frontend/src/pages/Explore.jsx`
- `frontend/package-lock.json`
- Promotes centralized data handling.
- Simplifies future updates to recipe content.
- Enhances scalability for new categories or dynamic rendering.
=> Refactor Explore Page with Centralized JSON Integration

frontend/src/App.jsx, frontend/src/components/Footer.jsx, frontend/src/pages/PrivacyPolicy.jsx, frontend/src/pages/TermsConditions.jsx
- privacy and terms pages added
-  added link in footer
-
=> added privacy and terms page

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/src/components/Footer.jsx, frontend/src/styles/Footer.css
This PR improves the overall UI/UX of the footer section across the website. The changes focus on making the footer more modern, consistent, and visually engaging while maintaining responsiveness.
##
Changes Made
##
Footer Layout
Improved grid structure for better spacing and alignment.
Adjusted typography hierarchy (headings, body text, and accent colors).
##
Links & Navigation
Added smooth hover animations with an underline slide effect.
Enhanced readability with subtle accent color (amber/red) for better emphasis.
##
Social Icons
Redesigned social media icons with circular backgrounds.
Added gradient hover effects and scale animations for better interactivity.
##
Footer Bottom
Refined legal links with underline hover effect.
Improved text contrast and spacing for a cleaner look.
## …
=> Improved footer UI

frontend/src/components/Header.jsx
- updated ui of menu bar
- 
@MeghanaDG04 #199
=> updated ui of menu bar

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Hi @MeghanaDG04  , i had added the desired templates please take a  look
Fixes #245
=> Added Templates

.github/workflows/issue-create-automate-message.yml, .github/workflows/pr-create-automate-message.yml
Hi @MeghanaDG04 , please take a look i had added the desired files .
Fixes #249
=> Added autocomment on PR and Issues

frontend/src/components/HowItWorksSection.jsx
Fixes #266 
Please include a summary of the changes and the motivation behind them.
Before:
After:
---
**Note for reviewers:**  
Please provide feedback and suggestions so this PR can be improved before merging 🚀
=> fixed undefined useNavigate variable

frontend/package-lock.json, frontend/src/components/HowItWorksSection.jsx
Fixes #307 
Please include a summary of the changes and the motivation behind them.
=> fix: corrected text visibility issue

frontend/src/components/Footer.jsx
Fixes : #329 
fixed the logo in the footer with the latest version
Before : 
After : 
---
**Note for reviewers:**  
Please provide feedback and suggestions so this PR can be improved before merging 🚀
=> [FEATURE] : old brand symbol in footer fixed 

frontend/src/pages/Login.jsx
This PR removes the unnecessary Terms & Conditions checkbox from the login page. The agreement validation logic and associated UI elements have been deleted to streamline the login experience, as this requirement is only relevant during registration.
=> Remove Terms & Conditions checkbox from login page
